default_agent: maritime_risk
agents:
  maritime_risk:
    name: maritime_risk
    language: python
    node_version: null
    entrypoint: src/maritime_risk/orchestrator.py
    deployment_type: container
    runtime_type: null
    platform: linux/amd64
    container_runtime: null
    source_path: null
    aws:
      execution_role: arn:aws:iam::813003568911:role/AmazonBedrockAgentCoreSDKRuntime-ap-southeast-1-169672948d
      execution_role_auto_create: false
      account: '813003568911'
      region: ap-southeast-1
      ecr_repository: 813003568911.dkr.ecr.ap-southeast-1.amazonaws.com/bedrock-agentcore-maritime_risk
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: true
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: maritime_risk-t5abDX7vOS
      agent_arn: arn:aws:bedrock-agentcore:ap-southeast-1:813003568911:runtime/maritime_risk-t5abDX7vOS
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-maritime_risk-builder
      execution_role: arn:aws:iam::813003568911:role/AmazonBedrockAgentCoreSDKCodeBuild-ap-southeast-1-943c0971f7
      source_bucket: bedrock-agentcore-codebuild-sources-813003568911-ap-southeast-1
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
